#define PTRSIZE 4
#define PTRTYPE uint32_t
#define PTRSIZEBITS PTRSIZE*8
#define PTRVALMASK ((1ULL << PTRSIZEBITS) - 1ULL)
#define UPBNDMASK  (~((1ULL << PTRSIZEBITS) - 1ULL))
#define MAXPTRVAL PTRVALMASK

#define SGXBOUNDS_RDACCESS    0
#define SGXBOUNDS_WRACCESS    1
#define SGXBOUNDS_RDWRACCESS  2
#define SGXBOUNDS_DEFACCESS   3
